In [1]:
#1D
import numpy as np
array1=np.array([1,2,3,4,5,6])
print(array1)


[1 2 3 4 5 6]


In [5]:
#2D
import numpy as np
array2=np.array([(1,2,3,4),(5,6,7,8)])
print(array2)
print(array2.itemsize)
print(array2.ndim)
print(array2.dtype)
print(array2.size)
print(array2.shape)

[[1 2 3 4]
 [5 6 7 8]]
8
2
int64
8
(2, 4)


In [11]:
import numpy as np
a=np.array([(1,2,3,4),(5,6,7,8)])
print(a.shape)
#print(a)
#a=a.reshape(4,2)
print(a)

print(a[0,2])


(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
3


In [17]:
import numpy as np
a=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print(a[0,3])
print(a[0:,3])

4
[ 4  8 12]


In [31]:
import numpy as np
a=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print(a[0,3])
print(a[0:,3])
print(a[0:2,3])
print(a[((1,2),(2,2))])

4
[ 4  8 12]
[4 8]
[ 7 11]


In [35]:
import numpy as np
array1=np.linspace(1,100,20)
print(array1)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [38]:
import numpy as np
a=np.array([(1,2,3,4),(5,6,7,8)])
print(np.sqrt(a))
print(np.std(a))
#print(a)

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
2.29128784747792


In [42]:
import numpy as np
ssp=np.array([(1,2,3,4),(5,6,7,8)])
print(ssp.max())
print(ssp.min())
print(ssp.sum())
print(ssp.sum(axis=0))
print(ssp.sum(axis=1))
print(ssp.ravel())

8
1
36
[ 6  8 10 12]
[10 26]
[1 2 3 4 5 6 7 8]


In [43]:
import numpy as np
a=np.array([(1,2,3,4),(5,6,7,8)])
b=np.array([(1,2,3,4),(5,6,7,8)])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 2  4  6  8]
 [10 12 14 16]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 1  4  9 16]
 [25 36 49 64]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [44]:
a=[1,3,5,7,9]
print(a[2:4])
b=[[1,3,5,7,9],[2,4,6,8,10]]
print(b[0])
print(b[1][2:4])


[5, 7]
[1, 3, 5, 7, 9]
[6, 8]


In [46]:
a=[1,3,5,7,9]
b=[3,5,6,7,9]
c=a+b
print (c)

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]


In [50]:
#as vectors from list
import numpy
a=numpy.array([1,3,5,7,9])
b=numpy.array([3,5,6,7,9])
c=a+b
print(c)
type(c)
c.shape


[ 4  8 11 14 18]


(5,)

In [56]:

import numpy
l=[[1,2,3],[3,6,9],[2,4,6]]  # create a list
print(l)
a=numpy.array(l) #convert a list to an array
print(a)
a.shape
print(a.dtype)   #get type of an array



[[1, 2, 3], [3, 6, 9], [2, 4, 6]]
[[1 2 3]
 [3 6 9]
 [2 4 6]]
int64


In [67]:
import numpy as np
#or directly as matrix
m=np.array([[1,2],[2,4]])
print(m.shape)
m.dtype
#m[0,0]="hello"
m=numpy.array([[1,2],[3,4]],dtype=complex)
print(m)

(2, 2)
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [68]:
import numpy as np
a=np.array([(1,2,3),(3,6,9),(2,4,6)])
print(a[0])   #like list of list
print(a[1,2])  #comma separated indices
print(a[1,1:3])  #slicing
print(a[:,1])
a[1,2]=7
print(a)
a[:,0]=[0,9,8]
print(a)


[1 2 3]
9
[6 9]
[2 6 4]
[[1 2 3]
 [3 6 7]
 [2 4 6]]
[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [74]:
import numpy as np
x=np.arange(0,10,1)   #start,stop,step
print(x)
np.linspace(0,10,25)
#np.logspace(0,10,10,base=np.e)

[0 1 2 3 4 5 6 7 8 9]


array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [79]:
import numpy as np
#a dimensional matrix
np.diag([1,2,3])

b=np.zeros(5)
print(b)
print(b.dtype)
n=1000
my_int_array=np.zeros(n,dtype=np.int)
my_int_array.dtype
c=np.ones((3,3))
print(c)

[0. 0. 0. 0. 0.]
float64
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [91]:
import numpy as np
x=np.arange(0,20,2)   #start,stop,step
print(x)
x[1]=15
print(x)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0 15  4  6  8 10 12 14 16 18]


In [93]:
import numpy
x,y=numpy.mgrid[0:5,0:5] #similar to meshgrid in MATLAB
print(x)
#random data
numpy.random.rand(5,5)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


array([[0.28241747, 0.12369084, 0.11737042, 0.62266312, 0.06469406],
       [0.19431955, 0.34808794, 0.43835508, 0.66536282, 0.85344021],
       [0.52938792, 0.52482835, 0.15615433, 0.71746701, 0.83872952],
       [0.04450593, 0.07599427, 0.96733179, 0.49941195, 0.94074381],
       [0.57464874, 0.60071829, 0.83080539, 0.35524804, 0.43422928]])

In [98]:
import numpy
m=numpy.random.rand(3,3)
print(m)
numpy.save('saved-matrix.npy',m)
numpy.load('saved-matrix.npy')
#os.system('head saved-matrix.npy')

[[0.16595866 0.7223206  0.19244337]
 [0.15874851 0.93931104 0.93020602]
 [0.67211781 0.43940739 0.26834635]]


array([[0.16595866, 0.7223206 , 0.19244337],
       [0.15874851, 0.93931104, 0.93020602],
       [0.67211781, 0.43940739, 0.26834635]])

In [108]:
import numpy
x=np.array([1,2,3,4])
y=x
x is y

print(id(x),id(y))

x[0]=9
print(y)

x[0]=1
z=x[:]
x is z

print(id(x),id(z))

x[0]=8
print(z)

x=np.array([1,2,3,4])
y=x.copy()
x is y

print(id(x))
print(id(y))

x[0]=9
print(x)

print(y)

140199614087040 140199614087040
[9 2 3 4]
140199614087040 140199614086880
[8 2 3 4]
140199614406704
140199614086720
[9 2 3 4]
[1 2 3 4]


In [6]:
import numpy
a=numpy.arange(4.0)
b=a*23.4
c=b/(a+1)
c+=10
print(c)

arr=numpy.arange(100,200)
select=[5,25,50,75,-5]
print(arr[select])  #can use integer lists as indices


arr=numpy.arange(10,20)
div_by_3=arr%3==0   #comparison produces boolean array
print(div_by_3)

print(arr[div_by_3]) #can use boolean lists as indices 

arr=numpy.arange(10,20).reshape((2,5))

[10.   21.7  25.6  27.55]
[105 125 150 175 195]
[False False  True False False  True False False  True False]
[12 15 18]


In [8]:
import numpy
arr.sum()

arr.mean()

arr.std()

arr.max()

arr.min()

div_by_3.all()

div_by_3.any()

div_by_3.sum()

div_by_3.nonzero()

(array([2, 5, 8]),)

In [11]:
import numpy
a=numpy.arange(0,100)
div_by_5=arr%5==0   #comparison produces boolean array
print(div_by_5)
print(arr[div_by_5])
arr.sum()

arr.mean()

arr.std()

arr.max()

arr.min()

div_by_5.all()

div_by_5.any()

div_by_5.sum()


[ True False False False False  True False False False False]
[10 15]


2

In [22]:
#sorting
import numpy
arr=numpy.array([4.5,2.3,6.7,1.2,1.8,5.5])
arr.sort()   #acts on array itself
print(arr)

x=numpy.array([4.5,2.3,6.7,1.2,1.8,5.5])
numpy.sort(x)

print(x)

s=x.argsort()   #accor to index position it will sort
print(s)
print(x[s])
#print(y[s])
arr.sum()
numpy.sum(arr)

[1.2 1.8 2.3 4.5 5.5 6.7]
[4.5 2.3 6.7 1.2 1.8 5.5]
[3 4 1 0 5 2]
[1.2 1.8 2.3 4.5 5.5 6.7]


22.0

In [35]:
#array operations
import numpy as np
a=np.array([[4,7],[4.0,3.0]])
print(a)

a.transpose()

print(np.linalg.inv(a))

#u=eye(2)  #unit 2*2 matrix;"eye" represents "I"

#print(u)

j=np.array([[0.0,-1.0],[1.0,0.0]])
np.dot(j,j)  #matrix product



[[4. 7.]
 [4. 3.]]
[[-0.1875  0.4375]
 [ 0.25   -0.25  ]]


array([[-1.,  0.],
       [ 0., -1.]])

In [41]:
#arrays and matrices
import numpy
m=numpy.mat([[1,2],[3,4]])
print(m)
  #or
a=numpy.array([[1,2],[3,4]])
print(a)
m=numpy.mat(a)
print(m)

#or
a=numpy.array([[1,2],[3,4]])
m=numpy.asmatrix(a)
print(m)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [53]:
#numpy-matrices
import numpy as np
a=np.array([[1,2],[3,4]])
m=np.mat(a)    #convert cd array to matrix
m=np.matrix([[1,2],[3,4]])
print(a[0])   #result is 1d
print(m[0])    #result is 2d

print(a*a)    #ele by ele  multiplication

print(m*m)   #algebraic matrix mul

print(a**3)   #elewise power

print(m**3)  #mat mul m*m*m

print(m.T)     #transpose 

print(m.H)     #conjugate transpose differs from .T for complex matrices

print(m.I)    #inverse matrix

[1 0]
[[1 2]]
[[1 0]
 [1 0]]
[[ 7 10]
 [15 22]]
[[1 0]
 [1 0]]
[[ 37  54]
 [ 81 118]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [56]:
#addition
import numpy as np
a=np.array([1,2,3],float)
b=np.array([5,2,6],float)
print(a+b)
print(a-b)
print(a*b)
print(b/a)
print(a%b)
print(b**a)

a=np.array([[1,2],[3,4],[5,6]],float)
b=np.array([-1,3],float)
print(a)

print(b)

print(a+b)

print(a*a)
print(b*b)
print(a*b)




[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[5. 1. 2.]
[1. 0. 3.]
[  5.   4. 216.]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[-1.  3.]
[[0. 5.]
 [2. 7.]
 [4. 9.]]
[[ 1.  4.]
 [ 9. 16.]
 [25. 36.]]
[1. 9.]
[[-1.  6.]
 [-3. 12.]
 [-5. 18.]]
