In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import graphviz
import sklearn as sk
from sklearn import ensemble
from collections import Counter
import os
#for each document in training set crete a frequency matrix for this words in dictionary and corresponding labels
def make_dict(root_dir):
    all_words=[]
    emails=[os.path.join(root_dir,f)
           for f in os.listdir(root_dir)]
    for mail in emails:
        with open(mail) as m:
            for line in m:
                words=line.split(' ')
                all_words+=words
    dictionary=Counter(all_words)
    list_to_remove=list(dictionary)

    #print(list_to_remove)
    
    for item in list_to_remove:
        if item.isalpha()==False:
            del dictionary[item]
        elif len(item)==1:
            del dictionary[item]
        dictionary=dictionary.most_common(3000)
        return dictionary
TRAIN_DIR="/home/dell/Desktop/train-mails"
TEST_DIR="/home/dell/Desktop/test-mails"
dictionary=make_dict(TRAIN_DIR)
print(dictionary)
        

[('_', 33602), ('.', 28582), ('-', 19192), (',', 18418), ('*', 17678), ('=', 8867), ('!', 5780), (':', 5200), ('/', 4893), (')', 4579), ('"', 4425), ('$', 4191), ("'", 4125), ('(', 3928), ('0', 1978), ('+', 1882), ('20', 1746), ('>', 1616), ('~', 1616), ('order', 1414), ("'s", 1355), ('#', 1324), ('address', 1297), ('report', 1216), ('mail', 1130), ('?', 1124), ('language', 1092), ('send', 1080), ('email', 1063), ('1', 1028), (';', 1025), ('program', 1004), ('our', 991), ('list', 941), ('one', 920), ('name', 880), ('2', 871), ('receive', 825), ('free', 799), ('money', 797), ('@', 757), ('work', 756), ("n't", 740), ('3d', 736), ('\n', 723), ('5', 695), ('information', 682), ('business', 667), ('please', 657), ('3', 640), ('e-mail', 598), ('university', 596), ('s', 583), ('us', 567), ('e', 565), ('day', 557), ('10', 549), ('follow', 544), ('internet', 532), ('\\', 528), ('over', 514), ('4', 502), ('call', 487), ('http', 479), ('check', 475), ('each', 466), ('include', 452), ('linguistic'

/home/dell/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
def extract_features(mail_dir):
    files=[os.path.join(mail_dir,fi) for fi in os.listdir(mail_dir)]
    features_matrix=np.zeros((len(files),3000))
    train_labels=np.zeros(len(files))
    count=0;
    docID=0;
    for fil in files:
        with open(fil) as fi:
            for i,line in enumerate(fi):
                if i==2:
                    words=line.split()
                    for word in words:
                        wordID=0
                        for i,d in enumerate(dictionary):
                            if d[0]==word:
                                wordID=i
                                features_matrix[docID,wordID]=words.count(word)
            train_labels[docID]=0
            filepathTokens=fil.split('/')
            lastToken=filepathTokens[len(filepathTokens)-1]
            if lastToken.startswith("spmsg"):
                train_labels[docID]=1
                count=count+1
            docID=docID+1
    return features_matrix,train_labels
TRAIN_DIR="/home/dell/Desktop/train-mails"
TEST_DIR="/home/dell/Desktop/train-mails"
extract_features(TRAIN_DIR)
features_matrix,labels=extract_features(TRAIN_DIR)
print(features_matrix,labels)

[[  0.  53.   2. ...   0.   0.   0.]
 [  0.  43.   0. ...   0.   0.   0.]
 [  0.   6.   0. ...   0.   0.   0.]
 ...
 [431.  53. 154. ...   0.   0.   0.]
 [217.  56.   2. ...   0.   0.   0.]
 [  0.  78.   4. ...   0.   0.   0.]] [1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1.
 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1.
 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1.
 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0.
 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1.
 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0.
 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1.
 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1.

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
TRAIN_DIR="/home/dell/Desktop/train-mails"
TEST_DIR="/home/dell/Desktop/train-mails"
dictionary=make_dict(TRAIN_DIR)
print("Reading and processing emails from file.")
#Creating Train_Data_Set
features_matrix,labels=extract_features(TRAIN_DIR)
#Creatin Test_Data_Set
test_feature_matrix,test_labels=extract_features(TEST_DIR)
model=RandomForestClassifier()
print("Training model")
#train model
model.fit(features_matrix,labels)
predicted_labels=model.predict(test_feature_matrix)
print("Finished classifying.accuracy score:")
print(accuracy_score(test_labels,predicted_labels))

Reading and processing emails from file.
Training model
Finished classifying.accuracy score:
0.9985754985754985
